### ISSUE TITLE
Status of job execution

### ISSUE THREAD

**Issue by silent-vim** [samuelcolvin/arq#102]
Hi, in arq is it possible to get the status of a job that has been submitted ? Currently for version 0.14 awaiting a job returns None. Is there a provision to get the job id and query the status.

**Comment by samuelcolvin** [comment]
Sorry answer: no, afraid not yet. 

I would like to add this, but haven't had time.

In the mean time you can set keys in redis to inform the main process that the job had started and finished.

**Comment by samuelcolvin** [comment]
fixed in v0.16a1
