### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by kobzar** [samuelcolvin/arq#117]
Hello. 
I try to select another RedisDB for create_pool
This is the simple code

 ```
   redis = await arq_create_pool(settings=RedisSettings(host='localhost', port=6379, database=3))
    job = await redis.enqueue_job('get_messages')
    print(job.job_id)
    print(await job.info())
    print(await job.status())
    print(await job.result())
```

When I use default settings, like a 
`redis = await arq_create_pool(RedisSettings())`
all working fine. 
For example
```
bf04177b3c7443778a6b0786b8b435ac
{'enqueue_time': datetime.datetime(2019, 4, 1, 12, 34, 15, 939000), 'job_try': None, 'function': 'get_messages', 'args': (), 'kwargs': {}, 'score': 1554122055939}
JobStatus.queued
[My data is here]
```

But when I try to use another database 
` redis = await arq_create_pool(settings=RedisSettings(host='localhost', port=6379, database=3))`
script is stuck on  `print(await job.result())`
In arq log I doesn't see any of actions actions 
In redis database3 I see only two keys
arq:queue = score :1554122478867, membe: ef48cff3cd0e46ec86b9c2ae8642491a
arq:job:ef48cff3cd0e46ec86b9c2ae8642491a = {}

Where is my mistake?

**Comment by kobzar** [comment]
I am understand. Just add config to my worker class like this
```
class WorkerSettings:
    functions = [get_messages]
    on_startup = startup
    on_shutdown = shutdown
    # redis_pool = 'redis'
    redis_settings = RedisSettings(host='localhost', port=6379, database=3)


class WorkerSettings1:
    functions = [send_mess]
    # on_startup = startup
    # on_shutdown = shutdown
    # redis_pool = 'redis'
    redis_settings = RedisSettings(host='localhost', port=6379, database=4)


class WorkerSettings2:
    functions = [send_mess2]
    # on_startup = startup
    # on_shutdown = shutdown
    # redis_pool = 'redis'
    redis_settings = RedisSettings(host='localhost', port=6379, database=5)
```

**Comment by samuelcolvin** [comment]
great, I was just about to reply and explain that.
