### ISSUE TITLE
sync tasks in arq?

### ISSUE THREAD

**Issue by dmfigol** [samuelcolvin/arq#124]
Hi,
thanks for your work.  
I am currently evaluating switching to async web framework and one big piece of my existing code is celery tasks. The problem is that not all of them can be converted to async because of the absence of underlying transport libraries.  
So the question is if it is possible to run sync tasks in a thread with arq?

**Comment by samuelcolvin** [comment]
Yes, absolutely, use [`run_in_executor`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor).

Closing the issue, but feel free to ask more questions if you need.

**Comment by dmfigol** [comment]
So something like this?
```
async def wrapped_blocking_task():
    loop = asyncio.get_running_loop()
    with concurrent.futures.ThreadPoolExecutor() as pool:
        result = await loop.run_in_executor(pool, my_blocking_task)
        return result
```

**Comment by samuelcolvin** [comment]
Yes, but I think you can leave `pool` as `None`.

In the past I've used a small wrapper like:

```py
async def run_in_executor(func, *args):
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, func, *args)
```

**Comment by dmfigol** [comment]
Perfect, thank you!

**Comment by Kamforka** [comment]
@samuelcolvin Will the `run_in_executor` solution also work with CPU intensive tasks, or it's only suitable for IO bound ones?

**Comment by samuelcolvin** [comment]
yes, https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor
