### ISSUE TITLE
WatchVariableError

### ISSUE THREAD

**Issue by pratheekrebala** [samuelcolvin/arq#131]
I'm getting a `aioredis.errors.WatchVariableError: ('WatchVariableError errors:', 'WATCH variable has changed')` when I'm running my queue.

I noticed that you had already raised a similar issue at: https://github.com/aio-libs/aioredis/issues/558

Are you still seeing the same issue using arq? Do you by chance have a workaround for this?

I have a simple queue setup and the only thing I'm doing differently is using `aioredis.create_sentinel_pool()` to generate the redis connection pool before feeding it to the `redis_pool` parameter on the worker.

```
    r = RedisConfig
    sentinel_client_pool = aioredis.sentinel.create_sentinel_pool(
        [(r.host, r.port)],
        db=r.database,
        password=r.password,
        timeout=r.timeout,
        encoding='utf8'
    )

    sentinel_client_pool = await sentinel_client_pool

    redis_master = sentinel_client_pool.master_for('mymaster')
    redis_pool = ArqRedis(redis_master)
```

**Comment by samuelcolvin** [comment]
I've prodded on that issue, maybe you could upvote it?

> Are you still seeing the same issue using arq?

I haven' seen the error recently so I'm not sure what to say.

Is likely that you're creating multiple jobs with the same key simultaneously?

**Comment by pratheekrebala** [comment]
Thanks for the super quick response!

Yup, that's probably what is happening. I will try and dig in further.

I just wasn't sure if it had something to do with the difference between the way the sentinel pool is implemented vs a regular Redis ConnectionPool.

**Comment by samuelcolvin** [comment]
I don't know as I haven't used sentinel pool, but I doubt it.
