### ISSUE TITLE
Support for redis sentinel 

### ISSUE THREAD

**Issue by pratheekrebala** [samuelcolvin/arq#132]
Is supporting something like Redis Sentinel within the scope of this project? I think it could be added with a few changes to `connections.py`.

If it is within scope, I can send in a PR.

**Comment by samuelcolvin** [comment]
by all means submit a PR, personally I don't use Sentinel, but provided it doesn't break other usage I'm happy to support it.

**Comment by pratheekrebala** [comment]
Apologies about the delay but I have something that's working locally for me here:

https://github.com/pratheekrebala/arq/commit/6ae8b654adc326d6ce9679aa871caaf147723b99

I will test further and confirm how well this works before the end of the weekend

**Comment by samuelcolvin** [comment]
great.

**Comment by pratheekrebala** [comment]
small PR available here to address this: https://github.com/samuelcolvin/arq/pull/151

**Comment by pratheekrebala** [comment]
#151 has a small issue which doesn't make sure that the connection is properly closed. Another PR #158 available to address this.

**Comment by nathanrobb** [comment]
Should this issue be resolved since #151 was merged, or am I missing something?

**Comment by samuelcolvin** [comment]
👍
