### ISSUE TITLE
Simple usage

### ISSUE THREAD

**Issue by kukirokuk** [samuelcolvin/arq#133]
Simple usage code here https://arq-docs.helpmanual.io/ does not work. Programm returns without any results. Please can you fix it?

**Comment by samuelcolvin** [comment]
It does work, what do you mean by "does not work"?

**Comment by kukirokuk** [comment]
@samuelcolvin When I ran it in command line arq demo.WorkerSettings it is working great, but when I do python demo.py. it just silently run without any results, what can be the reason?

**Comment by samuelcolvin** [comment]
running `python demo.py` shouldn't print anything, but you should see the output in the terminal where you're running `arq demo.WorkerSettings`

![image](https://user-images.githubusercontent.com/4039449/60450684-490e3600-9c22-11e9-91d7-64c2beb42775.png)

**Comment by kukirokuk** [comment]
Thanks, now its clear.
