### ISSUE TITLE
question

### ISSUE THREAD

**Issue by csrftoken** [samuelcolvin/arq#134]
I have a question, but I don't know what happened to it.
I run a timed arq task in production every two hours for the first minute，then I changed it to every night at 12:05，but it still runs every two hours.
May I ask if there is a command to check the execution time of timed tasks？

**Comment by csrftoken** [comment]
![image](https://user-images.githubusercontent.com/29940756/60584112-f1590180-9dbe-11e9-8858-6db8753b50a5.png)
I used a python process management tool to turn this task on or off.
And I'm thinking is it my code or is it from before?

**Comment by samuelcolvin** [comment]
afraid there's not enough information here for me to be able to help.

You should be able to inspect [`con.next_run`](https://github.com/samuelcolvin/arq/blob/master/arq/cron.py#L113).

**Comment by csrftoken** [comment]
Thanks.
