### ISSUE TITLE
Structured concurrency and more event loops

### ISSUE THREAD

**Issue by jtrakk** [samuelcolvin/arq#166]
This project looks very useful. I'd love to be able to use it with event loops that support [structured concurrency](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/). Currently the way to do this is via the [AnyIO library](https://anyio.readthedocs.io/en/latest/). This might mean a small change in public interface but with a large benefit in compatibility and structure. 

```py

async def main():
    conn = await connect(RedisSettings())
    async with conn.open_pool() as pool:
        for url in ('https://facebook.com', 'https://microsoft.com', 'https://github.com'):
            pool.enqueue_soon('download_content', url)

```

How would you feel about allowing an interface like that? 

---
FWIW - structured concurrency [chat](https://gitter.im/python-trio/general) and [forum](https://trio.discourse.group/).

**Comment by samuelcolvin** [comment]
Very happy to review a PR and discuss from there.

**Comment by Kludex** [comment]
This cannot be done unti aioredis makes use of anyio as well, or we use another redis client for trio.
