### ISSUE TITLE
Job uniqueness

### ISSUE THREAD

**Issue by JokerQyou** [samuelcolvin/arq#167]
The [doc][doc] says:

> arq supports this via custom job ids, see see arq.connections.ArqRedis.enqueue_job(). It guarantees that a job with a particular ID cannot be enqueued again until its execution has finished.

Which seems to imply that once a job has finished its execution, a new job with the same ID can be enqueued. But this is not true. If the job has result (return value, traceback information, etc.) left in Redis, new job with the same ID cannot be enqueued, see [these lines of code][code_enqueue]. In this case [the value of `keep_result` when initialize the worker][code_keep_result] would affect time duration of this conflict.

I think it's better to mention this in the `Job uniqueness` section.

  [doc]: https://arq-docs.helpmanual.io/#job-uniqueness
  [code_enqueue]: https://github.com/samuelcolvin/arq/blob/7c83a1d2ab90a0a811dabae0f6905788151a0737/arq/connections.py#L108-L110
  [code_keep_result]: https://github.com/samuelcolvin/arq/blob/7c83a1d2ab90a0a811dabae0f6905788151a0737/arq/worker.py#L165

**Comment by samuelcolvin** [comment]
yes true, happy to accept a PR to correct this in the docs.

**Comment by JonasKs** [comment]
Closed by #391
