### ISSUE TITLE
arq worker doesn't load new source code after reload in watch mode

### ISSUE THREAD

**Issue by vanyakosmos** [samuelcolvin/arq#168]
I tried minimal setup:

```python
from arq import cron

async def task(ctx):
    print("111")

class W:
    cron_jobs = [cron(task, second=0, run_at_startup=True)]
```

After launching worker with `arq test.W --watch .` I edited 4th line to `print("222")`. Worker restarted and when cron job triggered it printed `111` instead of `222`

logs:
```
.venv ❯ arq test.W --watch .
04:27:28: Starting worker for 1 functions: cron:task
04:27:28: redis_version=4.0.6 mem_usage=1.05M clients_connected=3 db_keys=3
04:27:29:   0.50s → cron:task()
111
04:27:29:   0.00s ← cron:task ●

files changed, reloading arq worker...
04:27:36: shutdown on SIGUSR1 ◆ 1 jobs complete ◆ 0 failed ◆ 0 retries ◆ 0 ongoing to cancel
04:27:36: Starting worker for 1 functions: cron:task
04:27:36: redis_version=4.0.6 mem_usage=1.05M clients_connected=3 db_keys=3
04:28:00:   0.50s → cron:task()
111
04:28:00:   0.00s ← cron:task ●
```

**Comment by vanyakosmos** [comment]
workaround is to run process via `watchgod`:
```
watchgod projects.test.main
```
where `package.test` is python module and `main` is function inside it that will run worker
```
def main(watch=None):
    logging.config.dictConfig(LOGGING_CONFIG)
    worker = Worker(
        (test_task1, test_task2),
        cron_jobs=[
            cron(test_task3, second={0, 10, 20, 30, 40, 50}, run_at_startup=True),
        ],
        redis_settings=get_redis_settings(),
        keep_result=0,
        on_startup=on_startup,
        on_shutdown=on_shutdown,
    )
    worker.run()
```

**Comment by euri10** [comment]
I've got almost the same issue but it seems a little bit different : on my side the reload happens fine in a local environment

but as soon as I switch to a container where the files watched are bind mounted into the container, the reload is not "seen" and is detected only once the container is stopped as you can see below

```
wait-for-it: waiting 15 seconds for redis:6379
wait-for-it: redis:6379 is available after 0 seconds
Loading redis settings
18:49:58: Starting worker for 1 functions: send_upload
18:49:58: redis_version=6.0.4 mem_usage=866.59K clients_connected=2 db_keys=0
18:50:15: shutdown on SIGUSR1 ◆ 0 jobs complete ◆ 0 failed ◆ 0 retries ◆ 0 ongoing to cancel
18:50:15: Starting worker for 1 functions: send_upload
18:50:15: redis_version=6.0.4 mem_usage=866.59K clients_connected=2 db_keys=0
18:52:14: shutdown on SIGUSR1 ◆ 0 jobs complete ◆ 0 failed ◆ 0 retries ◆ 0 ongoing to cancel
18:52:14: Starting worker for 1 functions: send_upload
18:52:14: redis_version=6.0.4 mem_usage=866.59K clients_connected=2 db_keys=0
18:52:20: shutdown on SIGUSR1 ◆ 0 jobs complete ◆ 0 failed ◆ 0 retries ◆ 0 ongoing to cancel
18:52:20: Starting worker for 1 functions: send_upload
18:52:20: redis_version=6.0.4 mem_usage=866.59K clients_connected=2 db_keys=0
18:52:23: shutdown on SIGUSR1 ◆ 0 jobs complete ◆ 0 failed ◆ 0 retries ◆ 0 ongoing to cancel
18:52:23: Starting worker for 1 functions: send_upload
18:52:23: redis_version=6.0.4 mem_usage=846.12K clients_connected=1 db_keys=0
18:52:26: shutdown on SIGUSR1 ◆ 0 jobs complete ◆ 0 failed ◆ 0 retries ◆ 0 ongoing to cancel
18:52:26: Starting worker for 1 functions: send_upload
18:52:26: redis_version=6.0.4 mem_usage=846.12K clients_connected=1 db_keys=0
18:52:33: shutdown on SIGTERM ◆ 0 jobs complete ◆ 0 failed ◆ 0 retries ◆ 0 ongoing to cancel

files changed, reloading arq worker...

files changed, reloading arq worker...

files changed, reloading arq worker...

files changed, reloading arq worker...

files changed, reloading arq worker...
```

I thought at first it was because of vim in containers, but I experienced the very same weird behavior if I `:set backupcopy=yes` or if i use another editor.

Not sure i should report that upstream or if anyone have thoughts on how to deal with it, seems more like a docker / volume issue, but given how widespread it is now to use containers in dev mode I thought maybe it was a good place to start reporting this given how close it is to op issue.

**Comment by samuelcolvin** [comment]
Correct me if I'm wrong, but surely this is a problem with watchgod (also my problem 😞 )?

Might be solved by https://github.com/samuelcolvin/watchgod/issues

If not let me know and I'll reopen.

**Comment by euri10** [comment]
> Correct me if I'm wrong, but surely this is a problem with watchgod (also my problem  )?
> 
> Might be solved by https://github.com/samuelcolvin/watchgod/issues
> 
> If not let me know and I'll reopen.

this is where it's ambiguous to be, I'm not sure it's upstream here's why:

I added to my docker-compose file the `tty: true` to the container running arq and it solved the weird reload described above, so now it looks fine in the logs BUT:

```
wait-for-it: waiting 15 seconds for redis:6379
wait-for-it: redis:6379 is available after 0 seconds
Loading redis settings
15:04:02: Starting worker for 1 functions: send_upload
15:04:02: redis_version=6.0.4 mem_usage=846.65K clients_connected=1 db_keys=2
15:04:14:   0.42s → d5aae278dbeb4125b4af31f49e89a79a:send_upload('COURSE_34621299.gpx')
15:04:15:   1.00s ← d5aae278dbeb4125b4af31f49e89a79a:send_upload ● 'COURSE_34621299.gpx'

files changed, reloading arq worker...
15:04:21: shutdown on SIGUSR1 ◆ 1 jobs complete ◆ 0 failed ◆ 0 retries ◆ 0 ongoing to cancel
15:04:21: Starting worker for 1 functions: send_upload
15:04:21: redis_version=6.0.4 mem_usage=867.45K clients_connected=2 db_keys=3
15:04:28:   0.30s → af49a9b963d34625a7dece1574ca671e:send_upload('Le Gendarme de St Tropez 1964-1982 720p BluRay DD5 1 x264-WiKi.torrent')
15:04:29:   1.00s ← af49a9b963d34625a7dece1574ca671e:send_upload ● 'Le Gendarme de St Tropez 1964-1982 720p BluRay DD5 1 x264-WiKi.torrent'
```

in the above log the `send_upload` method  was rightfully reloaded, watchgod detected it, but the time spent  on processing the job stayed the same (it's a dummy job that just waits 1s and the reloaded happened because I entered 5s), see:

```
async def send_upload(ctx, filename):
    logger.debug(f"Processing: {filename}")
    await asyncio.sleep(1) # I switched it to 5 and the reload happened
    return filename
```

so it seems to me the file is reloaded, but it has no effect and it still operates on the "old" file.

I tried with vim (both backupcopy options), with nano and get same results.

I also tried to write a syntax error in my worker job imports on purpose and still the job executes fine in 1s.

I'm not saying it's arq, it's probably a conjunction of docker, maybe docker-compose, but I'm not sure it belongs upstream now I get the reload message.

**Comment by euri10** [comment]
I'd also be interested if op @vanyakosmos has the issue locally or in containers, would be helpul

**Comment by vanyakosmos** [comment]
in containers

**Comment by euri10** [comment]
ok I take back the fact that it's working locally, sorry for the confusion

in fact I have the very same behavior locally where modifying the job function reloads the file well, but the function itself is not updated and after reload it's still processing the old function.

so I think that is worth reopening the issue

seems like the task `async_run` just re-creates the task without checking if the self.functions in the Worker have changed, not sure if that would be the place to do that,

https://github.com/samuelcolvin/arq/blob/eee0b661de1288f9d0a17fcdd4838743303c94c2/arq/worker.py#L237-L242

**Comment by samuelcolvin** [comment]
getting python to reload code properly is a nightmare.

We should probably use a subprocess to run the whole of arq, then kill that process and start a new one to reload.

**Comment by SamiAlsubhi** [comment]
> > Correct me if I'm wrong, but surely this is a problem with watchgod (also my problem  )?
> > Might be solved by https://github.com/samuelcolvin/watchgod/issues
> > If not let me know and I'll reopen.
> 
> this is where it's ambiguous to be, I'm not sure it's upstream here's why:
> 
> I added to my docker-compose file the `tty: true` to the container running arq and it solved the weird reload described above that was happening kind of too late, so now it looks fine in the logs BUT:
> 
> ```
> wait-for-it: waiting 15 seconds for redis:6379
> wait-for-it: redis:6379 is available after 0 seconds
> Loading redis settings
> 15:04:02: Starting worker for 1 functions: send_upload
> 15:04:02: redis_version=6.0.4 mem_usage=846.65K clients_connected=1 db_keys=2
> 15:04:14:   0.42s → d5aae278dbeb4125b4af31f49e89a79a:send_upload('COURSE_34621299.gpx')
> 15:04:15:   1.00s ← d5aae278dbeb4125b4af31f49e89a79a:send_upload ● 'COURSE_34621299.gpx'
> 
> files changed, reloading arq worker...
> 15:04:21: shutdown on SIGUSR1 ◆ 1 jobs complete ◆ 0 failed ◆ 0 retries ◆ 0 ongoing to cancel
> 15:04:21: Starting worker for 1 functions: send_upload
> 15:04:21: redis_version=6.0.4 mem_usage=867.45K clients_connected=2 db_keys=3
> 15:04:28:   0.30s → af49a9b963d34625a7dece1574ca671e:send_upload('Le Gendarme de St Tropez 1964-1982 720p BluRay DD5 1 x264-WiKi.torrent')
> 15:04:29:   1.00s ← af49a9b963d34625a7dece1574ca671e:send_upload ● 'Le Gendarme de St Tropez 1964-1982 720p BluRay DD5 1 x264-WiKi.torrent'
> ```
> 
> in the above log the `send_upload` method was rightfully reloaded, watchgod detected it, but the time spent on processing the job stayed the same (it's a dummy job that just waits 1s and the reloaded happened because I entered 5s), see:
> 
> ```
> async def send_upload(ctx, filename):
>     logger.debug(f"Processing: {filename}")
>     await asyncio.sleep(1) # I switched it to 5 and the reload happened
>     return filename
> ```
> 
> so it seems to me the file is reloaded, but it has no effect and it still operates on the "old" file.
> 
> I tried with vim (both backupcopy options), with nano and get same results.
> 
> I also tried to write a syntax error in my worker job imports on purpose and still the job executes fine in 1s.
> 
> I'm not saying it's arq, it's probably a conjunction of docker, maybe docker-compose, but I'm not sure it belongs upstream now I get the reload message.

I am facing the exact same issue. Did you find a solution? @euri10

**Comment by euri10** [comment]
> I am facing the exact same issue. Did you find a solution? @euri10

nope, I have to restart

**Comment by KShah707** [comment]
Still no progress on a solution?

**Comment by vidjuheffex** [comment]
just want to add, that following the docs and using --watch, I still have to reload arq
