### ISSUE TITLE
Add support for job depends_on filed like rq

### ISSUE THREAD

**Issue by elatt** [samuelcolvin/arq#175]
It would be nice for our workload if `arq` had some sort of support for chaining jobs like in `rq` (i.e. [depends_on](https://github.com/rq/rq/blob/ed15b9e031eab74f2216f333883321be78bd4056/docs/docs/index.md))

**Comment by samuelcolvin** [comment]
Thanks for the suggestion.

I think this would be very difficult to implement in an efficient way within arq. Better to create a single job that calls multiple functions which can also be jobs themselves.

**Comment by romankolpak** [comment]
@elatt did you find a way to implement this nicely with `arq`?

**Comment by elatt** [comment]
I believe we ended up just doing as was suggested: having a "meta" job that just orchestrated calling and waiting on sub jobs.
