### ISSUE TITLE
concurrent control

### ISSUE THREAD

**Issue by shaozi** [samuelcolvin/arq#176]
Hi I have a question on how to use arq:

I have some tasks (e.g. fetch web contents) that needs to be executed in parallel, with max say 5 workers simultaneously, 
while at the same time, I have another set of tasks (e.g. update database) that needs to be executed one by one.

Both types of task should be executed at the same time.

in rq, I created 2 queues, and 5 workers on queue-1, and 1 worker on queue-2.
 
How do I achieve this with arq?

Thanks!

**Comment by u-ashish** [comment]
You can still use separate queues.

When you enqueue, specify a `queue_name`: `https://arq-docs.helpmanual.io/_modules/arq/connections.html#ArqRedis.enqueue_job`

And when you initialize the worker, specify the corresponding `queue_name` there: `https://arq-docs.helpmanual.io/_modules/arq/worker.html#Worker`
