### ISSUE TITLE
Callback on job status change

### ISSUE THREAD

**Issue by steinitzu** [samuelcolvin/arq#179]
In my app I want to send websocket events when jobs start running and when they complete.

If I could call an async function with job object or id+status or something like that when job progresses I could achieve this.

Is there any way to do this in arq right now? I wouldn't mind subclassing the worker, but couldn't find an appropriate place to put this kind of logic.

**Comment by samuelcolvin** [comment]
I would say best just to all those async functions at the beginning and and of each job function.

If you have many such job functions you could even create a decorator or context manager to avoid duplication.

Does that work?

**Comment by steinitzu** [comment]
Yeah the decorator approach should work, I was considering that as well. Just wanted to see if there was some easy way to hook into the worker that I missed :)

Thanks for the snappy response.
