### ISSUE TITLE
Running arq inside another async app

### ISSUE THREAD

**Issue by kdorsel** [samuelcolvin/arq#182]
I want to run arq from within another app that controls the asyncio event loop (FastAPI).

I've been able to start it up and get it working, but the issue is on shutdown where arq catches the sigint/sigterm signals and these never get passed up. This makes the process hang in a dead state.

```
class Worker:
    def __init__(self):
        pass

    async def start(self):
        # loop = asyncio.get_event_loop()
        self.worker = create_worker(worker_settings)
        # loop.remove_signal_handler(SIGINT)
        # loop.remove_signal_handler(SIGTERM)
        self.task = asyncio.create_task(self.worker.async_run())

    async def close(self):
        logger.debug("Starting worker close")
        await self.worker.close()
        logger.debug("Ending worker close")
```

I've found that if I remove the loop's signal handlers that arq created I can exit, but this throws errors since no signal handlers are now present.

Signal handlers are added here:
https://github.com/samuelcolvin/arq/blob/master/arq/worker.py#L215
```
        self._add_signal_handler(signal.SIGINT, self.handle_sig)
        self._add_signal_handler(signal.SIGTERM, self.handle_sig)
```

In the app startup/shutdown I will startup/shutdown arq as necessary, but would need an option to pass in to prevent arq from registering its own handlers.

**Comment by samuelcolvin** [comment]
happy to accept a PR to add this setting.
