### ISSUE TITLE
Allow job to finish during SIGINT for graceful shutdown

### ISSUE THREAD

**Issue by u-ashish** [samuelcolvin/arq#192]
I've deployed multiple workers in docker containers via swarm in our VM.

During a release, swarm will send a `SIGINT` (followed eventually by a `SIGKILL`) to bring down old images and bring up new ones.

During a `SIGINT`, instead of doing a `task.cancel()` and retrying, would it be possible to:
- Stop it from taking new jobs from the queue if it gets a `SIGINT`
- Try to finish what it has now & mark job as done if success
- Then shutdown on the `SIGKILL`

Our jobs are retryable so the existing behavior of cancelling and retrying isn't a huge problem, but it can rarely lead to scenarios that require us to cleanup after (the workers do a bit of fetching files from sources, manipulating them, moving them to other buckets, updating DBs, etc., so some artifacts can remain if cancelled in the middle of a job).

Looking at the worker source code, it looks like on both `SIGINT` and `SIGKILL` it does `handle_sig` (which just gets the tasks and cancels if not done).

Would it be possible to expose `handle_sig` so a user can specify custom handling on `SIGINT` (e.g. what I described above)?

Thanks for reading (and for the awesome lib!!)

**Comment by samuelcolvin** [comment]
The behaviour works the way it does for good reason, I don't think this requires a change in arq.

You can either:
* use `shield` to prevent critical tasks from being cancelled
* catch the `CancelError` inside the task, cleanup and re-raise it
* or, override `handle_sig` on the worker to implement your own custom behaviour

**Comment by u-ashish** [comment]
Ah, sorry I didn't see I could already override `handle_sig` -- that was all I needed. Sorry for missing that.
