### ISSUE TITLE
Raise Exception on Existing Jobs

### ISSUE THREAD

**Issue by TimOrme** [samuelcolvin/arq#208]
Thanks for making `arq`!

This is maybe more of a usability suggestion, but currently `enqueue_job` method will return `None` in the event that a job with the same ID already exists.  It makes sense for this case to be handled when the job ID is passed to `enqueue_job`.

However, for many uses we don't pass the job ID so we should never expect the job ID to already exist.  But because the return signature of `enqueue_job` is `Optional[Job]` we end up with some sort of awkward code to make the type checker happy:

```
job = await myarq.enqueue_job("method", some_arg)
if job:
    return job.job_id
else:
    raise RuntimeError("This should never happen")
```

I think for the more typical use case, the expectation is that something like this should work:

```
job = await myarq.enqueue_job("method", some_arg)
return job.job_id
```

Instead, it might be better to have `enqueue_job` raise a "JobAlreadyExists" error instead of returning `None` for these cases.  That way, the above block works, and if users want to handle that case, they still can do so by catching the exception:

```
try:
    job = await myarq.enqueue_job(job_id=123, "method", some_arg)
except JobAlreadyExists as e:
    ...
```

One downside here is that we introduce a breaking change.  But if this seems reasonable, I'm happy to open a PR to add the functionality!

Relevant lines are here: https://github.com/samuelcolvin/arq/blob/master/arq/connections.py#L115

**Comment by samuelcolvin** [comment]
I think the current interface is fine, in 3.8 you can reduce this slightly to 4 (very clear) lines of code

```py
if job := await myarq.enqueue_job("method", some_arg):
    return job.job_id
else:
    raise RuntimeError("This should never happen")
```

**Comment by inactivist** [comment]
@samuelcolvin Would you mind sharing your rationale for returning None from `enqueue_job` in this situation (and thus requiring the conditional logic if one wishes to make use of the `job.id` metadata after the `enqueue_job` call?)

I'm trying to understand if you consider trying to enqueue a job already present in the queue as an exceptional condition requiring special handling, etc.
