### ISSUE TITLE
Question about poll_delay

### ISSUE THREAD

**Issue by qbx2** [samuelcolvin/arq#210]
Hello, I am new to redis and arq.
I found that there is poll_delay for Worker, and that Worker polls for jobs every 0.5 sec by default. My question is that could the delay reduce throughput? If it could, how about using pub/sub model to receive push notifications (poll now)? Would this idea improve the performance of arq?

**Comment by samuelcolvin** [comment]
It won't make any difference.

Redis (even on a small deployment) can happily cope with thousands of queries a second.

Once your workload increases the polling will become irrelevant as every new query gets extra jobs.
