### ISSUE TITLE
Registries concept (or analogue)

### ISSUE THREAD

**Issue by nikkonrom** [samuelcolvin/arq#217]
RQ has concept of Registries: objects that represents state of given queue by holding jobs that have status corresponding to registry type (e.g. Failed Job Registry that holds failed jobs for queue, Finished Job Registry that holds finished jobs for queue, Queued Job Registry that holds queued jobs for queue etc.). So there is easy way to observe current status of queue by checking it's registries and then retrieve jobs via registry to display or manage.
Is similar concept exists in arq or can it be done other way?

**Comment by samuelcolvin** [comment]
you can get data about queued jobs by getting the underlying sorted set which is used as the queue.

There's no equivalent of a failed jobs queue, instead arq has a more sophisticated retry model built in.

There's no finished queue, but you could easily add something to redis on each job if you needed to know about finished jobs.
