### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by erakli** [samuelcolvin/arq#220]
Hello, 

Seems arq wasn't updated since October. Also, there's some good PR's to be reviewed.

@samuelcolvin do you plan any updates to project?

**Comment by samuelcolvin** [comment]
Ok, I'll try over Christmas.

**Comment by 2foil** [comment]
Waiting for the new release. :)

**Comment by erakli** [comment]
@samuelcolvin take a look, please!

**Comment by erakli** [comment]
@samuelcolvin friendly ping :small_airplane:

**Comment by samuelcolvin** [comment]
Sorry sorry sorry, been so busy.

Will do at the end of the week.

**Comment by samuelcolvin** [comment]
I've gone through all PRs and merged what I can, I'll now give authors a few days to fix PRs and respond where appropriate, after that I'll merge all PRs (fixing them myself if required) and make the new release.

Sorry again for the delay.

**Comment by samuelcolvin** [comment]
v0.20 is released at last.

Please try it and create issues if you find any bugs, there are quite a lot of big refactors in this release to support `job.abort()` and cron job uniqueness.
