### ISSUE TITLE
Unable to use unique job_id twice

### ISSUE THREAD

**Issue by ikhomutov** [samuelcolvin/arq#221]
It seems like you cannot use same job_id for another task, if the first task was finished and there is a 'result' key for this job_id in redis. Is it an expected behavior? If so, how can I change this?

**Comment by ikhomutov** [comment]
Ah, nevermind. Found a comment in https://github.com/samuelcolvin/arq/pull/138 about setting *keep_result* parameter.

**Comment by ross-nordstrom** [comment]
@samuelcolvin it might be worth updating the docs for this. The bit on Job Uniqueness disagrees with the current behavior (which seemed to change in #138 as mentioned)
> It guarantees that a job with a particular ID cannot be **enqueued again until its execution has finished**.

https://arq-docs.helpmanual.io/#job-uniqueness


Anyways, the `keep_result` workaround solved it for me.  It would also be nice to be able to set the `keep_result` on a per job basis in case I end up with more flavors of jobs with different result-retention needs.

**Comment by samuelcolvin** [comment]
Pr welcome to update the docs.

**Comment by KShah707** [comment]
> It would also be nice to be able to set the `keep_result` on a per job basis in case I end up with more flavors of jobs with different result-retention needs.

I think you can, if you use the `arq.worker.func` wrapper to declare your job: https://arq-docs.helpmanual.io/#arq.worker.func
