### ISSUE TITLE
Python 3.8 is not supported by arq

### ISSUE THREAD

**Issue by dgl-ableton** [samuelcolvin/arq#223]
When running the [simple usage example](https://arq-docs.helpmanual.io/#simple-usage) with Python 3.8.6, I get this error
```
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<RedisConnection._read_data() running at /Users/dgl/Code/devtools-repos/uberflask/venv/lib/python3.8/site-packages/aioredis/connection.py:186> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x111020ee0>()]> cb=[RedisConnection.__init__.<locals>.<lambda>() at /Users/dgl/Code/devtools-repos/uberflask/venv/lib/python3.8/site-packages/aioredis/connection.py:168]>
```
However, when run with Python 3.7.0, the example runs totally fine. Let me know if should provide more information.

**Comment by samuelcolvin** [comment]
What OS are you using? It looks from the path like it might be macos, I have a feeling this might be an issue specific to macos, but I'm not sure.

**Comment by dgl-ableton** [comment]
I'm currently using macOS Catalina 10.15.7

**Comment by samuelcolvin** [comment]
thanks for confirming.

I'm too busy to look into this myself right now, but I'll happily review a fix if you can find one.

It would be good as a start to confirm if this is related to macos, or linux too.

**Comment by rtzll** [comment]
I've got the same issue on Ubuntu 20.04 with Python 3.8.5:
```
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<RedisConnection._read_data() running at /home/cr/src/arq-example/.venv/lib/python3.8/site-packages/aioredis/connection.py:186> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f8b24046a00>()]> cb=[RedisConnection.__init__.<locals>.<lambda>() at /home/cr/src/arq-example/.venv/lib/python3.8/site-packages/aioredis/connection.py:168]
```

**Comment by Tinche** [comment]
This looks like a shutdown problem? We've been running Arq on 3.8 in production for a long time now and it works well for us.

**Comment by rtzll** [comment]
Not sure if this is related, but I ran the tests and `tests/test_worker.py:75 test_handle_sig` is failing most of the time. I've run it multiple times and 3 out of 4 runs it's failing.

```
ERROR    asyncio:base_events.py:1707 Task was destroyed but it is pending!
task: <Task pending name='Task-1848' coro=<SentinelPool.__init__.<locals>.echo_events() running at /home/cr/src/arq/.venv/lib/python3.8/site-packages/aioredis/s
entinel/pool.py:86> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2d27738ac0>()]>>```

**Comment by Tinche** [comment]
Ah, that test looks to be for handling signals. We run Arq alongside other asyncio components and thus we handle signals ourselves, so I can't comment on that functionality.

**Comment by scainet** [comment]
This works for me

```python
async def main():
    redis = await create_pool(RedisSettings())
    for url in ('https://facebook.com', 'https://microsoft.com', 'https://github.com'):
        await redis.enqueue_job('download_content', url)
    redis.close()
    await redis.wait_closed()
```

**Comment by cmangla** [comment]
If I launch `main()` using `asyncio.run()` then the examples don't display the above error message. It's probably still worth closing the connection as @scainet has shown above. Related PR #226 .

**Comment by Kludex** [comment]
@scainet Solution works for me! :)
