### ISSUE TITLE
Dynamic cron

### ISSUE THREAD

**Issue by thiras** [samuelcolvin/arq#224]
Hello,

Is there a way to get the corn values (like minutes, hours, etc.) dynamically?

**Comment by 2foil** [comment]
Moreover, how to add cron jobs dynamicly?

**Comment by samuelcolvin** [comment]
These are two different questions:
1. I'm not sure if the question. You mean in the cron job itself? I think that's not currently possible, but I suspect it wouldn't be that hard to add it to context.
2. I believe this is not currently possible.
