### ISSUE TITLE
CPU bound tasks

### ISSUE THREAD

**Issue by Kludex** [samuelcolvin/arq#227]
Hi there!

I'm creating a cookiecutter analogous to https://github.com/tiangolo/full-stack-fastapi-postgresql/ for FastAPI, but instead of Celery, I'm using arq. I'm enjoying it, so thank you!

Anyway, I have a question. Hope you guys can help me. :kissing:

So, what would be the best way to handle CPU bound tasks with arq? As it's a worker, I assumed that there's no problem to block the event loop, as I can schedule more worker instances. Is my assumption right?

If it's not, as I don't have the opportunity to run an executor inside the worker, what would be the recommended approach?  

Thank you in advance! :)

**Comment by erakli** [comment]
Block the event loop looks like bad solution. The only way I could recommend is a spawning thread/process in multi-core env. But before doing this, I think that you must check if there's more than one CPU-core.

**Comment by Kludex** [comment]
> If it's not, as I don't have the opportunity to run an executor inside the worker, what would be the recommended approach?

What I said is just not true. I can spawn threads with `asyncio.run_in_executor()` inside the task itself. This pattern is fine.

I'll probably use this helper (or the logic that is being used): https://github.com/django/asgiref/blob/7921bf04dfa71cebc9294e8f06936cdb63166674/asgiref/sync.py#L280

Thank you.

**Comment by samuelcolvin** [comment]
sorry not to respond earlier.

You're exactly right, `loop.run_in_executor` is your friend.

Note:
* you'll need to use a `ProcessPoolExecutor` if your task is CPU bound, if it's disk bound or IO bound without using asyncio, you can still with `ThreadPoolExecutor`
* if you're using `ProcessPoolExecutor` a lot, you might want to set up a process pool to reuse in jobs rather  than creating a new process on each job

**Comment by Kludex** [comment]
@samuelcolvin Thank you for answering. :)

> if you're using ProcessPoolExecutor a lot, you might want to set up a process pool to reuse in jobs rather than creating a new process on each job

Would it make sense to do something like this?

```python
from concurrent import futures

async startup(ctx):
    ctx['pool'] = futures.ProcessPoolExecutor(max_workers=2)

async shutdown(ctx):
   ctx['pool'].shutdown()
```

**Comment by samuelcolvin** [comment]
Exactly

**Comment by Kludex** [comment]
Thank you!
Have a nice day! :smile:

**Comment by gerazenobi** [comment]
@samuelcolvin hi 👋 

I was having more or less the same question: we chose `Arq` to process jobs that will be doing IO bound work. 
However, we have other Jobs that are CPU bound. We were then planning to simply have 2 different queues, let's say `io-bound` , `cpu-bound` and have 2 different sets of workers for each of them: e.g. a pod worker 1 (light, low cost) for io and a pod worker 2 for cpu bound (more expense, more power). **We are ok with pod 2 blocking each time it processes a job, and processing 1 job at a time.**

Is there any issue or caveat we should be aware of in doing the above ?
