### ISSUE TITLE
Settings with uvloop

### ISSUE THREAD

**Issue by Kludex** [samuelcolvin/arq#228]
Hi there again!

I just want to have a confirmation. But it actually helps others as a showcase... 

I was wondering if `handle_signals` is the only worker configuration I need to pay attention when using it with `uvloop`. Is that the case?

This is what I have:

```python
import asyncio

import uvloop

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

async def print_num(ctx, num: int):
    print(num)

async def startup(ctx):
    print("start")

async def shutdown(ctx):
    print("end")

class WorkerSettings:
    functions = [print_num]
    on_startup = startup
    on_shutdown = shutdown
    handle_signals = False
```

Thank you in advance! :)

**Comment by cmangla** [comment]
Do you need to do `uvloop.install()` somewhere? You can also double-check it in the `startup` function like so:

```python3
async def startup(ctx):
    l = asyncio.get_event_loop()
    if isinstance(l, uvloop.Loop):
        print("uvloop is being used")
```

**Comment by Kludex** [comment]
`uvloop` is being used... That's not quite my question. I was wondering if I need to take care of something else.
