### ISSUE TITLE
remove result

### ISSUE THREAD

**Issue by jackielii** [samuelcolvin/arq#229]
Firstly, thanks for this amazing lib!

In our use case, we would like to keep the result. Currently using a work around by setting the job to `keep_result=timedelta(days=365)`. 

However, we found removing the result seems no so straightforward.

**Comment by meseta** [comment]
just to add: we would also find this useful. In our use-case, a task in arq returns a path to where a file was produced. This file is later deleted to free up space. We'd like to remove the result so that it can't be requested again, as the path is no longer valid

**Comment by samuelcolvin** [comment]
I believe #205 allows you to keep results indefinitely, unless I'm mistaken I believe that's what your want.

**Comment by meseta** [comment]
We kind of need the opposite - keep results forever until manually removed. It's the "manual removal" that is needed, rather than keeping results forever

**Comment by YuriiMotov** [comment]
Faced the same problem. Is it possible to clear job's results manually?
