### ISSUE TITLE
How to catch tasks that failed after retries

### ISSUE THREAD

**Issue by kornicameister** [samuelcolvin/arq#233]
Hey everyone,

I am trying to figure out if there's a way to catch a moment when tasks fails to execute after X retries.
I.e. we have `max_retries=10` but 10th retry fails too and I need to grab that moment to send something somewhere.

```python
raise arq.Retr(...)  # that fails, because max_retries is reached
```

How can it be done? Is there a watcher, callback of some sort?

**Comment by samuelcolvin** [comment]
I don't think there's a specific place you can do this, you'll need to do the logic just before you raise the retry exception.

**Comment by kornicameister** [comment]
that's exactly how I approached that problem.
