### ISSUE TITLE
Terminated

### ISSUE THREAD

**Issue by chicksick** [samuelcolvin/arq#236]
Hi, maybe its stupid question. Why several tasks not started and print just "Terminated"? Maybe there are some python memory limits or something else? Thanks.

**Comment by samuelcolvin** [comment]
I'm not clear about the question?

**Comment by chicksick** [comment]
I have a worker which pulls ~50-100 tasks from queue every hour and performs some calculations. Several tasks fail to start and line "Terminated" appears in my terminal.

**Comment by samuelcolvin** [comment]
The string `Terminated` doesn't appear anywhere in the arq codebase, so I don't think this is specific to arq.

To help, you'd need to dig further and work out where the "Terminated" is coming from.
