### ISSUE TITLE
Rename pole_delay to poll_delay

### ISSUE THREAD

**Issue by johtso** [samuelcolvin/arq#241]
I guess the right way would be to add the new argument, and raise a deprecation warning for the misspelled argument?

https://github.com/samuelcolvin/arq/search?q=pole

**Comment by samuelcolvin** [comment]
Good find, just me being dyslexic. I'll create a PR.

**Comment by johtso** [comment]
I initially thought it might be technical term with a subtly different meaning that I hadn't come across! :)

**Comment by samuelcolvin** [comment]
**"Pole Delay"**
_expression._

_Time taken to hit the ground._

![time taken to hit the ground](https://media.giphy.com/media/3ornjUjpZFUztYw18I/source.gif)

**Comment by samuelcolvin** [comment]
Should be fixed by #242, let me know what you think.
