### ISSUE TITLE
cron job timzone config

### ISSUE THREAD

**Issue by kjh03160** [samuelcolvin/arq#251]
Hi, I wanna use cron utils according to my timezone, not utc default.
But I cannot find how can I set the timezone.
In Worker setting contexts which are given to cron func, there are `"enqueued_time"` key and datetime utc value.
Can I handle this value? or any other approach for changing utc timezone?

**Comment by samuelcolvin** [comment]
my instinct is that this isn't possible since we using unix timestamps to denote when jobs should start.

Can't you just run a job every hour or whatever, and check if it's the right time (in your timezone) using your own logic?

**Comment by kjh03160** [comment]
If it is impossible, I would handle jobs in my own logic. Thanks

And another question
Is it not possible to use `Retry` in cron jobs?
If I add `Retry` in my cron job coroutine function, it raises Exception of `delete() missing argument 'key'` in AioReids when cron job fails.

I want to use `Retry` feature, so I changed my logic like below.
1. Make cron job doing `enqueue_job` to put my function in scheduler
2. then scheduler pop it and runnging.

However, I encountered `WARN: Task was destroyed but it is pending!`. Even if the function has been run, I want to fix these warning. 

If you have any solution or better idea, please tell me.

Thanks in advance.

**Comment by samuelcolvin** [comment]
if you need that functionality, probably easiest to just create a job from the cron job, then in that second job you can use `Retry` etc. as normal.
