### ISSUE TITLE
Is it possible to implement worker listen from different instance in arq?

### ISSUE THREAD

**Issue by SudheendraSoftionik** [samuelcolvin/arq#252]
Hey Guys,

Is it possible to implement worker listen from different instance in arq?

For example in rq we have option like this 

rq worker --url redis://:secrets@example.com:1234/ 

Do we have same kind of feature in arq?

Thanks.

**Comment by shakks** [comment]
Hey, can the reverse of this be possible. If I have a worker listening to a queue, can I increase the thru put by adding additional worker for the same task. 

In other works 2 worker listening to same queue and performing same task increasing the thru-put.

**Comment by samuelcolvin** [comment]
yes, you can have as many workers as you like processing jobs from the same queue.
