### ISSUE TITLE
redis connection error - TimeoutError 

### ISSUE THREAD

**Issue by filipematos95** [samuelcolvin/arq#260]
Hello, 

I am always getting:
` redis connection error ('localhost', 6379) TimeoutError , 5 retries remaining...
`

I am on Win10 using arq==0.21 and aioredis==1.3.1
Any clue what might be?

**Comment by n8sty** [comment]
You need to have an instance of Redis running and available at port 6379. That error indicates that you can't connect to Redis. Ensure that you're running Redis on port 6379 (the default port).
