### ISSUE TITLE
python 3.10 support

### ISSUE THREAD

**Issue by euri10** [samuelcolvin/arq#282]
greetings @samuelcolvin 
I was trying to test arq on python 3.10.0 and I'm kind of going in circles :snake:  

1. arq uses aioredis 1.3.1 
2. there is a bug on python 3.10.0  (https://bugs.python.org/issue45416) which prevent that version of aioredis to function correctly `        self._cond = asyncio.Condition(lock=Lock())`

what do you think would be the best way to proceed ? 

It seems like trying to push https://github.com/samuelcolvin/arq/pull/259 is the right move however, I haven't check precisely if aioredis 2.x was hit but the python bug (for which there is a workaround) 

I could also ask if aioredis intends to fix the 1.3.1 version, which would sort the 1st blocker I'm facing on this.

let me know your thoughts, thanks !

**Comment by Apakottur** [comment]
Just in case it's useful, I had the same problem so I patched our code with the fix (which is added in 3.10.1):
```python
def _patch_asyncio_condition():
    """
    Apply a bugfix in asyncio.Condition that is added towards Python 3.10.1.
    Once we update to Python 3.10.1, this patch can be removed.
    See:
        https://github.com/python/cpython/commit/164dddf5f8c9c6b93f32c9f79b4301fc804576e9
    The bug affects an internal call to asyncio.Condition in `arq` which is used by this module.
    This function will raise a RuntimeError once we upgrade to 3.10.1, and should be removed.
    Raises:
        RuntimeError: If the Python version is not 3.10.0 and the function should be removed.
    """

    def _patched_condition_init(self, lock=None, *, loop=asyncio.mixins._marker):  # type: ignore
        super(type(self), self).__init__(loop=loop)
        if lock is None:
            lock = asyncio.Lock()

        self._lock = lock
        # Export the lock's locked(), acquire() and release() methods.
        self.locked = lock.locked
        self.acquire = lock.acquire
        self.release = lock.release

        self._waiters = collections.deque()

    if platform.python_version() == "3.10.0":
        asyncio.Condition.__init__ = _patched_condition_init  # type: ignore
    else:
        raise RuntimeError("Looks like Python was updated, remove the patch to asyncio in this module.")
```
