### ISSUE TITLE
Alternative backend

### ISSUE THREAD

**Issue by ergo** [samuelcolvin/arq#284]
Is there a plan or a least a way to plug in other backend than redis for `arq`? In the past (using celery mostly) I've seen that rabbitmq can perform better, provides also better visibility into how the system operates - especially since redis in LRU mode might be losing data on a full database (not sure how lists of tasks behave here).

**Comment by samuelcolvin** [comment]
no plan to support other backends, it would make the library massively more complex.

**Comment by 1hachem** [comment]
@samuelcolvin how about https://www.dragonflydb.io 
its a faster drop-in replacement for redis, I think it wont increase the complexity

I would like to open a pr for this, and I would like to know what you think?
