### ISSUE TITLE
FastAPI + arq: exceptions are not raised

### ISSUE THREAD

**Issue by satinfive** [samuelcolvin/arq#287]
Hello!
I started using arq within FastAPI. I've been facing lots of problems and re-execution of jobs to understand exactly what was happening.
Following the idea in #245 i launch hundreds of jobs managed by a main job which awaits the result of all of them and then do some operations.
All seemed to start pretty well, jobs were completed by time. However at certain point all of the single jobs appears with a 'complete' status in redis, as well as the main job, but the final step which was upload a file wasn't. 
I tried to debug it and I realized the main job wasnt complete actually, it failed. So the normal workflow is a series of retries which actually happened. However, at certain line of code, the job just stopped its execution and then you start at the beginning, ready for a new retry. The last line the job execute every retry is when an internal exception happens, but that pass silently, making the jobs fail.

My question: is this the normal behavior? If so, how can I do to raise an internal exception everytime sometimes fails within the jobs? 

Thanks!

**Comment by waza-ari** [comment]
I noticed that exception handling is not particularly well done unfortunately. I guess that you have `retry_jobs` set to `true`?

Check here: https://github.com/samuelcolvin/arq/blob/4c70063bd62046fb94f0a0b5096bf0a35b62b26a/arq/worker.py#L541

```
except (Exception, asyncio.CancelledError) as e:
            finished_ms = timestamp_ms()
            t = (finished_ms - start_ms) / 1000
            if self.retry_jobs and isinstance(e, Retry):
                incr_score = e.defer_score
                logger.info('%6.2fs ↻ %s retrying job in %0.2fs', t, ref, (e.defer_score or 0) / 1000)
                if e.defer_score:
                    incr_score = e.defer_score + (timestamp_ms() - score)
                self.jobs_retried += 1
            elif job_id in self.aborting_tasks and isinstance(e, asyncio.CancelledError):
                logger.info('%6.2fs ⊘ %s aborted', t, ref)
                result = e
                finish = True
                self.aborting_tasks.remove(job_id)
                self.jobs_failed += 1
            elif self.retry_jobs and isinstance(e, (asyncio.CancelledError, RetryJob)):
                logger.info('%6.2fs ↻ %s cancelled, will be run again', t, ref)
                self.jobs_retried += 1
            else:
                logger.exception(
                    '%6.2fs ! %s failed, %s: %s', t, ref, e.__class__.__name__, e, extra={'extra': exc_extra}
                )
                result = e
                finish = True
                self.jobs_failed += 1
```

This is essentially the `except` block around the job execution. You'll notice that if `retry_jobs` is true, the exception will be silently ignored and instead the job is being retried. Even if that is not set to true, the exception is logged and not raised, so its not possible to implement custom exception handling either. 

There is not much you can do I fear.

**Comment by samuelcolvin** [comment]
What does "raise the exception" mean? Crash the worker? Doesn't sound very helpful.

You need to be careful to catch errors in your code. If you want to report that back to the process which started the job (e.g. fastapi) you can use your own logic, or arq results.

**Comment by waza-ari** [comment]
I agree, crashing the worker doesn't seem to be a good idea. 

@samuelcolvin just to give an idea why I'm arguing (and please don't understand this as critique, I love arq in general):

In my case, I am looking for a way to customise the way exceptions are send to logging such that my logging solution can act accordingly without the need to parse multi-line logs. Overriding the `sys.excepthook` does no good in this case obviously, as the exceptions are handled internally.

Obviously is does no good just raising the Exceptions, it would require the caller to make sure they're handled. What I would wish for would be either a flag to control how exceptions are handled, or an optional function that can be passed to handle the exceptions. 

Do you think that's a way to cover such cases?
