### ISSUE TITLE
How does Arq behave when there is data loss?

### ISSUE THREAD

**Issue by johtso** [samuelcolvin/arq#300]
I'm currently trying to get my head around the idea of using Arq + Redis for a payment flow on a website. Redis obviously isn't designed for maximum robustness.. once a second persistence to disk is a common configuration.

Any thoughts on how badly things would break if the Redis instance lost some data?

I guess with the "run at least once" design it would be fine if we lost the write that said "this job has been completed".. we would just run the job again?

It would be more of an issue if we lost the write that says "this job is being run by a worker".. then there could be a job stuck in limbo.

Maybe the design already factors in the possibility of data loss? Just trying to figure out what kinds of failure modes I should be considering, grateful for any input!

**Comment by samuelcolvin** [comment]
The design factors in the idea that redis might go down or the python server might go down. But I'm not pretending it would be robust to the kinds of data loss you're talking about.

The robust answer is:
* right the job info to an ACID database like postgres
* trigger the job
* have a cron job that runs fairly regularly and checks postgres for any old and uncompleted jobs

Hope that helps?
