### ISSUE TITLE
How to stop receiving new jobs?

### ISSUE THREAD

**Issue by Olegt0rr** [samuelcolvin/arq#302]
I wanna use `arq` workers to execute long tasks. 

Sometimes I need to update the code. 
So it would be nice to up a new version of `arq` worker and make old one to stop receiving new jobs, but finish all the current.

Is there any way to do it?

**Comment by samuelcolvin** [comment]
Nothing built in I'm afraid. Wouldn't be too hard to implement, PR welcome.

**Comment by Olegt0rr** [comment]
@JonasKs, I imagine it as a bool flags. E.g. `is_stopping`.

On `is_stopping` we can:
a) pause the queue reading
b) continue reading, but ignore queued jobs

**Comment by JonasKs** [comment]
Makes sense to me. I’d suggest `process_tasks`. 

Since the worker is already running you’d have to change this in redis. This could be stored as a flag in redis, where you set it on each worker ID. ( #291 )

**Comment by michaelmernin** [comment]
@JonasKs 
@samuelcolvin 

Am also interested in this feature, have tried overriding the handle_sig function with successes so far.

`def custom_handle_sig(worker, sig):
    worker.main_task and worker.main_task.cancel()
    worker.on_stop and worker.on_stop(sig)
 
arq.worker.Worker.handle_sig = custom_handle_sig`

 A couple questions:
- Is there any validity to the above approach?
- If so, could we just add a flag that allows us to bypass the cancellation logic directly in handle_sig function?
 
Example:
`def handle_sig(self, signum: Signals) -> None:
        sig = Signals(signum)
        if not "CUSTOM_TAG":
            task_action = "cancel"
            for t in self.tasks.values():
                if not t.done():
                    t.cancel()
        else:
            task_action = "complete"
       
        logger.info(
            'shutdown on %s ◆ %d jobs complete ◆ %d failed ◆ %d retries ◆ %d ongoing to %s',
            sig.name,
            self.jobs_complete,
            self.jobs_failed,
            self.jobs_retried,
            len(self.tasks),
            task_action,
        )
        self.main_task and self.main_task.cancel()
        self.on_stop and self.on_stop(sig)`

**Comment by JonasKs** [comment]
This is closed by #345.
