### ISSUE TITLE
Stuck jobs in queue

### ISSUE THREAD

**Issue by Olegt0rr** [samuelcolvin/arq#316]
**Question:**
Why some tasks queued but not going to execution? 
New task processed by workers immediately.

**Healthcheck:**
`Jun-20 10:35:06 j_complete=6 j_failed=1 j_retried=0 j_ongoing=1 queued=10`

**WorkerSettings:**
`max_jobs = 10`

**Workers:**
`4 replicas`
<img width="603" alt="Screenshot 2022-06-20 at 14 39 26" src="https://user-images.githubusercontent.com/25399456/174593889-97e94b37-cbe0-4ff3-a1d6-e58580635b18.png">
CPU, RAM and drive space is OK.

**Redis:**
<img width="488" alt="Screenshot 2022-06-20 at 14 40 46" src="https://user-images.githubusercontent.com/25399456/174594103-b4500078-81fe-47fa-b06b-4e5f2b029b18.png">
12 items - is OK, because 2 was added after health check.

**Comment by JonasKs** [comment]
Please look at #343, you have to also check if the `arq:retry` or `arq:in-progress` have the same GUID.

**Comment by Olegt0rr** [comment]
I increase `job_timeout` cause my job may work up to 3 days - it's okay

**Comment by JonasKs** [comment]
Then it is because of what I wrote in #343 and this is intended. 😊 I think this issue can be closed.

**Comment by Olegt0rr** [comment]
@JonasKs, so what should I do with long tasks? May be restart timeout and "auto-kill" timeout should be separate?

**Comment by JonasKs** [comment]
The only way would you build in a health check of some sort from the worker, as suggested in the other issue. 

What you should do is honestly to split your tasks into multiple steps (tasks), or to use `func` to set only a high timeout on your long tasks, so all other tasks can have a more sensible timeout.

**Comment by samuelcolvin** [comment]
Good answer.
