### ISSUE TITLE
Jobs get expired after ~24 hours non-depending on job_timeout

### ISSUE THREAD

**Issue by Ezhvsalate** [samuelcolvin/arq#320]
Hello!

We are using arq in production for more than a year already and I want to thank you for your great job at first.

Unfortunately, we met an issue with long-running jobs containing multiple retries.

There are jobs tracking whether long-running scientific calculations are done.  They look for a specified file on NFS, if there is no -  raise Retry(defer=10).  Every single retry runs quite quickly. 

Following settings are set for worker:
```
    max_tries = 1000000
    job_timeout = 300000
```

Actually after ~24 hours job is expired: 
`worker_3    | 2022-07-20 23:28:36.223 | WARNING  | arq.worker:run_job:391 - job 761f60bfc7724e10bd9e4f913f7acd75 expired`

What I found [in arq code](https://github.com/samuelcolvin/arq/blob/master/arq/worker.py#L416) nearby line mentioned in logs:

```
            pipe.expire(retry_key_prefix + job_id, 88400)
            ...
            await self.pool.setex(retry_key_prefix + job_id, 88400, str(job_try))
```

Could someone please explain, what is this magic number `88400` seconds (which is about 24.5 hours).
Is this an upper limit of `job_timeout` time? How can I make a job run longer? 

Another question is how is `job_timeout` parameter applied? Intuitively I thought that it's a maximum time how long each retry of a job can run. But now it looks like if it is calculated for all retries of one job.

Appreciate your help!

**Comment by samuelcolvin** [comment]
Should be fixed by #303?
