### ISSUE TITLE
Not possible to deserialize arq job outside the Python environment which created it

### ISSUE THREAD

**Issue by iamlikeme** [samuelcolvin/arq#339]
I was considering writing a standalone utility for visualizing status and metadata of arq jobs by reading data from redis when I realized that, in general, it is not possible to deserialize a job outside of the Python environment where it was created.

By default jobs are serialized using `pickle` which implies that my standalone utility has to be written in Python. But even in Python, unpickling will fail if the job result, error or any of job arguments is an object of a type which is not in the standard library. For example, if a job fails with a SQLAlchemy exception, then the job data (including basic information such as `success`, `start_time`, `finish_time`, etc.) stored in redis can only be deserialized in a Python environment where SQLAlchemy is installed.

Perhaps responsibility of the serializer/deserializer could be reduced to handling only the args, kwargs and result, so that output from a serializer (bytes) could be e.g. base64 encoded and written with the rest of medatada to JSON. This would greatly improve interoperability and allow creating third-party tools for working with arq, which itself is meant to small, simple and limited in scope.

**Comment by samuelcolvin** [comment]
that's already support ans I believe we even have unit tests for using msgpack.

See [Custom Job Serializers](https://arq-docs.helpmanual.io/#custom-job-serializers)

**Comment by iamlikeme** [comment]
Thank you for getting back to me. I haven't thought about using custom serializers.

So it is possible to write a custom serializer which does pickle+base64 on values for keys "a" (args), "k" (kwargs) and "r" (result) before formatting the whole job dict to JSON, but such solution seems too tightly bound to the internal implementation details of arq. But on the other hand, any tool which would read arq's data directly from Redis would have to know these internal details, so I guess the question was ill posed.
