### ISSUE TITLE
Differentiate results when using single redis with multiple services

### ISSUE THREAD

**Issue by euri10** [samuelcolvin/arq#344]
In https://github.com/samuelcolvin/arq/pull/191 was introduced the default queue name for the following reason:

> When using a single central Redis with multiple services, it's necessary to use different queues.

It would be very helpful for pretty much the same reason to be able to differentiate the results of different queues, currently all arrive under `arq:result:jobid`

Would you consider a PR leaning towards that goal ?

**Comment by JonasKs** [comment]
Closing in favor of #346
