### ISSUE TITLE
testing nested jobs when the queue name is not default fails as child job is sent to default queue

### ISSUE THREAD

**Issue by euri10** [samuelcolvin/arq#348]
Let's say you have an arq service `myarq.py`, that is not using the default queue name and where there is a parent job that triggers a child job.

The parent / child job in  `myarq.py`  looks like the nested job test in the test suite ie:
```
    async def foobar(ctx):
        return 42

    async def parent_job(ctx):
        inner_job = await ctx['redis'].enqueue_job('foobar')
        return inner_job.job_id
```
I run the `myarq.py`using a 
```
class WorkerSettings:
    functions = [
foobar, parent_job
    ]
    on_startup = startup
    on_shutdown = shutdown
    redis_settings = RedisSettings.from_dsn(app_settings.redis_url)
    queue_name = "another"

```
and `arq myarq:WorkerSettings`

A web app triggers the parent job with `await arq_redis.enqueue_job('parent_job')` and arq_redis has been well defined to have the same "another" queue name :+1: 
```
  arqredis = await arq.create_pool(
            r, default_queue_name="another"
        )
```

when using locally and "manually" all is ok, the web app endpoint triggers the parent job that triggers foobar, so no worries on that front.

the issue is in my tests, using the very same fixture as in the test suite I do

```
worker: Worker = worker(queue_name="another", functions=[func(parent_job, name='parent_job'), func(foobar, name='foobar')])
await worker.main()
```

and here, only the parent is triggered in the test, the child is sent to "arq:queue" !

so I'm wondering whether of not it is a bug (since it seems to me just an issue testing wise), if I should explicitely in my `my_arq.py` file specify the queue_name the child job has to be sent to with `        inner_job = await ctx['redis'].enqueue_job('foobar', _queue_name="another")`or if there's anything obvious I'm missing.

thanks for any insights.

**Comment by JonasKs** [comment]
Hmmmm, since it works when running it properly, I'd assume something with the tests, without looking close at it 😁 

You can always just change the default queue name in your tests:
```python 
arq_redis.default_queue_name = "another"
await arq_redis.enqueue_job('spawn_foobar', _job_id='testing', _queue_name="another")
```

Alternatively do this:
```python
inner_job = await ctx['redis'].enqueue_job('foobar', _queue_name="another")
```

**Comment by JonasKs** [comment]
Ah.. 

```python
  arqredis = await arq.create_pool(
            r, default_queue_name="another"
        )
```
Here you define the `default_queue_name` when creating the `arq connection`. `enqueue_job` defaults to the connection default_queue_name if you do not give it an explicit queue name. 

If you'd like to change this behavior you can change the `arq_redis` fixture to also edit the default queue name.

```python
@pytest.fixture
async def arq_redis_another_queue(loop):
    redis_ = ArqRedis(
        host='localhost',
        port=6379,
        encoding='utf-8',
        default_queue_name='another'
    )

    await redis_.flushall()

    yield redis_

    await redis_.close(close_connection_pool=True)
```

I'll close this issue, as I believed it has been answered. Please let me know if you have any more questions or we should investigate more.

**Comment by euri10** [comment]
I honestly dont remember the exact details about this when I was trying to set up different queues names, so take this with caution.

But after I spent quite a fair amount of time on it (but obviously not enough to tackle it), the dx has been very painful and I ended up not using it because there's currently no way to differentiate the result, retries on non-default names.

In that precise case I would definitely prefer my tests / app to crash loud and clear when using non-default parameters rather than the current behaviour where it's half-working and send the jobs to unexpected queues.

It's entirely possible that this was a misusage on my side though, that said I find the current possibility offered in configuring this part of arq comes at too great a cost of understanding how and if it's working as intended, while using the defaults is painless dx-wise.

**Comment by JonasKs** [comment]
It's important to understand the difference between the Worker and the client(s). When you run a worker, you tell it which queue to use. On an entirely different machine, you can run clients, which can queue tasks. This works well.  
The problem you seemed to experience with the test setup is that the ArqConnection is already configured with a default and passed to the worker, instead of established on startup like it would be when you do this:

```python
redis_settings = from_dsn(...
```
I never re-created your problem, but I'll give it a go and see if I can make the fixture more consistent with what runtime behavior is. 

With that said, when I looked through all issues yesterday, I agree, there is confusion around queues and it's behavior.  
I believe solving #346 would be a great start, while also try to ensure that anything written in the worker settings becomes the default.
