### ISSUE TITLE
Launch Workers programmatically

### ISSUE THREAD

**Issue by kamkash** [samuelcolvin/arq#356]
Is there a way to launch Workers programmatically? 
Without using the arq cli?

**Comment by samuelcolvin** [comment]
Yes, I'm on my mobile so can't look at code right now.

Not too hard if you look though the code.

**Comment by kamkash** [comment]
I will look, but appreciate sample code when you have a chance.

**Comment by kamkash** [comment]
ahh.  Is it as simple as this:

```
from arq.worker import (
    Worker
)

    class Settings:
        functions = [func(foobar, name='foobar')]
        burst = True
        poll_delay = 0
        queue_read_limit = 10


    worker = run_worker(Settings)

```
