### ISSUE TITLE
Read error due to coroutines waiting for incoming data with upcoming redis-py

### ISSUE THREAD

**Issue by chayim** [samuelcolvin/arq#365]
We're releasing redis-py 4.4.0 shortly, but there's a [bug](https://github.com/redis/redis-py/issues/2407) we could use a hand with. I've asked a couple of folks to have a look at things, in case they can assist but wanted to read out here in case you can help.

Ideally, I don't want us releasing 4.4.0 until [bug](https://github.com/redis/redis-py/issues/2407)  is fixed on our side, given [your dependency](https://github.com/samuelcolvin/arq/blob/9ce2fd6ae4694584ec8b0ff78a1e4e3359ae3a44/pyproject.toml#LL41C29-L41C29) - but we'd like to release within the next day or so. Sorry for the short notice - I'd like to not have negative impact! 

As an aside - I ran all of the arq tests locally, with the most recent redis-py (4.4.0rc4) things definitely fail, as per the bug linked.

**Comment by samuelcolvin** [comment]
Thanks for notifying me, I've replied on https://github.com/redis/redis-py/issues/2407

Happy to review a PR, or I'll try to fix it later in the week.

**Comment by JonasKs** [comment]
Closed in #366
