### ISSUE TITLE
How to get jobs in order to abort

### ISSUE THREAD

**Issue by dokime7** [samuelcolvin/arq#376]
Hi and thanks for this work!

In order to abort some deferred jobs, I need to get an instance of `arq.jobs.Job` but I don't find how to get jobs.
I'm using FastAPI with an endpoint to enqueue job and another to abort job, so I don't have the job instance returns by `enqueue_job()`.

How can I do that?

Thanks

**Comment by JonasKs** [comment]
Hi, please see https://github.com/samuelcolvin/arq/issues/372#issuecomment-1342497550.

**Comment by dokime7** [comment]
Thanks, it could be help, but I can't always save the job id.

I've seen that `queued_jobs()` can return a list of `JobDef`, so I can retrieve a `JobDef` by matching an external id on `kwargs` but `JobDef` doesn't return job id...

**Comment by JonasKs** [comment]
Aha, I can fix that.

**Comment by dokime7** [comment]
It would be great 👍🏼 👌🏼
