### ISSUE TITLE
Datetime in next_cron func doesn't have timezone information 

### ISSUE THREAD

**Issue by TyrPhoonn** [samuelcolvin/arq#380]
I have one issue at line 47 in `cron.py` return next_datetime values without timezone information.
I think it will be happen when your frequency_time greater than now and next_cron will move to next year.
You can try with current time and next_cron is any day of next year.

You can use this code to replace while loop at line 43
```
while True:
    next_dt = _get_next_dt(dt, options)
    if next_dt is None:
        return dt.replace(tzinfo=datetime.now().astimezone().tzinfo)
    dt = next_dt
```

**Comment by JonasKs** [comment]
Maybe @iamlikeme who built tz aware cron jobs has any insight here? 😊 I won't be able to look into this for a while.

**Comment by JonasKs** [comment]
PRs with tests always welcome 🙏

**Comment by iamlikeme** [comment]
Thanks @TyrPhoonn for reporting the bug, and thanks @JonasKs for pinging me :+1: I submitted a PR with a bugfix.
