### ISSUE TITLE
question on order of jobs

### ISSUE THREAD

**Issue by acivitillo** [samuelcolvin/arq#388]
Coming from this [answer](https://github.com/samuelcolvin/arq/issues/262#issuecomment-905424808). I had a quick follow up question regarding this sentence: ```arq uses a sorted set, jobs are added with a timestamp after which they should be run```

Does this mean we can order jobs simply using `_defer_by`?

```python
job1 = await ArqRedis.pool.enqueue_job("some_high_priority_job")
job2 = await ArqRedis.pool.enqueue_job("some_lower_priority_job", _defer_by=0.01)
job3 = await ArqRedis.pool.enqueue_job("some_even_lower_priority_job", _defer_by=0.02)
```

In the above case, assuming job1, job2 and job3 might receive the same timestamp, we add `_defer_1` of a few centiseconds to create an order.

Is this correct?

**Comment by JonasKs** [comment]
Sorry for the late reply, I missed this one. 

Yea, that's how it's supposed to work. You can test logic like this yourself by making your worker only process one task at the time, and then queue tasks as you have done in your example. 

I don't know your use case, but if you want tasks to be chained, queueing task 1, and then make that task queue task 2 is the way to go.
