### ISSUE TITLE
job.result() hangs indefinitely if queue_name other than "arq:queue" is used

### ISSUE THREAD

**Issue by AlexanderPodorov** [samuelcolvin/arq#390]
In `WorkerSettings`:
If `queue_name = "arq:queue"` is used, then everything works as expected. In case if I take e.g. `arq:queue:something`, `job.result()` hangs indefinitely. Looks like `"arq:queue"` name is hardcoded somewhere causing this issue.
Nevertheless, thanks for this awesome library!

**Comment by JonasKs** [comment]
Can you provide a reproducible example? 

Seems to me that the job is passed along: https://github.com/samuelcolvin/arq/blob/main/arq/connections.py#L171

**Comment by AlexanderPodorov** [comment]
Ah, yes, I did not set `_queue_name` of `enqueue_job` method, so it took the default queue name. I just set queue name in `WorkerSettings`. If the issue is actually the expected behavior, I can close this issue.

**Comment by JonasKs** [comment]
That is the expected behavior indeed 😊 you can have multiple workers and queues.

**Comment by AlexanderPodorov** [comment]
Got it, thanks, issues is closed
