### ISSUE TITLE
print() not being displayed in honcho or Dokku

### ISSUE THREAD

**Issue by RamonGiovane** [samuelcolvin/arq#393]
Hi, my `print()` calls inside the jobs are not working properly when ARQ is containerized, like using a Procfile and running [honcho](https://github.com/nickstenning/honcho) or when it's deployed in Dokku.

I have this function being scheduled:

```python
async def run_bgc_recaps(ctx):
    """My cron task."""
    print('teste')

class RecapWorker(BaseWorker):
    """My worker settings."""

    cron_jobs = [
        cron(run_bgc_recaps, hour=[3, 15], minute=30),
    ]
    queue_name = 'recap_queue'
    redis_settings = REDIS_SETTINGS

```

My Procfile:
```bash
web: make run
recap-worker: arq bgc.workers.recap_worker.RecapWorker
```

Executing the worker standalone:
![image](https://user-images.githubusercontent.com/40267373/231480578-d156ca95-c156-4a61-ae09-4523903746af.png)
**_Works fine._**

Executing the worker in a Procfile container with honcho.
![image](https://user-images.githubusercontent.com/40267373/231480653-eb1d79ea-842e-455b-a709-8f594ff0562b.png)
**_Never prints until honcho is aborted. Note the keyboard interrupt and then the print._**

I never had any `stdout` issues inside containers, I guess it's some configuration that must be done with ARQ or with the `logger` module, but I don't know, never did it before and could not find any clue in the docs.

**Comment by samuelcolvin** [comment]
Have you tried `flush=True`?

Doesn't sound related to arq.

**Comment by JonasKs** [comment]
This isn't the fix you want I guess, but you should probably consider using logs instead of prints. Seems like those works as intended.

**Comment by RamonGiovane** [comment]
@samuelcolvin  Thanks, it worked!
Also, here's something that Honcho's documentation say:

> By default, Python will buffer a program’s output more aggressively than Ruby when a process has STDOUT connected to something other than a TTY. This can catch people out when running Python programs through Honcho: **if the program only generates small amounts of output, it will be buffered, unavailable to Honcho, and will not display.**
> 
> One way around this is to set the PYTHONUNBUFFERED environment variable in your Procfile or your .env file. Be sure you understand the performance implications of unbuffered I/O if you do this.
> 
> For example:
>` myprogram: PYTHONUNBUFFERED=true python myprogram.py`

With that said, I tried both approaches and both worked:
```python
print('teste', flush=True)
```

```
recap-worker: PYTHONUNBUFFERED=true arq bgc.workers.recap_worker.RecapWorker
```


It just makes me wonder, I've played a bit with other frameworks + Honcho (fastapi, celery, rq) and I have never faced this before.  Maybe that's why some frameworks print out a massive amount of things, sometimes useless, on startup? Is it just to avoid things being buffered? :thinking: 
![image](https://user-images.githubusercontent.com/40267373/231561105-a5cf8669-2272-40d9-9df9-45886da8748b.png)

**Comment by RamonGiovane** [comment]
> This isn't the fix you want I guess, but you should probably consider using logs instead of prints. Seems like those works as intended.

Hi, @JonasKs 

You may be right, but I guess I need to configure something, because it looks worse now :confused: 

```python
import logging
async def run_rfc_recaps(ctx):
    """My cron task."""
    logging.debug('teste')
```

Running in both ways, it prints out like this:
```
17:47:00 recap-worker.1 | 17:47:00:   1.00s → cron:run_rfc_recaps()
17:47:00 recap-worker.1 | INFO:arq.worker:  1.00s → cron:run_rfc_recaps()
17:47:00 recap-worker.1 | 17:47:00:   0.00s ← cron:run_rfc_recaps ● 
17:47:00 recap-worker.1 | INFO:arq.worker:  0.00s ← cron:run_rfc_recaps ● 

17:48:00 recap-worker.1 | 17:48:00:   1.00s → cron:run_rfc_recaps()
17:48:00 recap-worker.1 | INFO:arq.worker:  1.00s → cron:run_rfc_recaps()
17:48:00 recap-worker.1 | 17:48:00:   0.00s ← cron:run_rfc_recaps ● 
17:48:00 recap-worker.1 | INFO:arq.worker:  0.00s ← cron:run_rfc_recaps ●
```

**Comment by samuelcolvin** [comment]
well that's the default logging formatter, you'll need to customise the formatter.

Please check https://docs.python.org/3/library/logging.html

**Comment by RamonGiovane** [comment]
@samuelcolvin I was just confused why print wasn't working with ARQ on Dokku, but I learned how to config the logging module, it was a better option indeed. Thanks :smiley: :+1:
