### ISSUE TITLE
The future of arq

### ISSUE THREAD

**Issue by AlexanderPodorov** [samuelcolvin/arq#414]
Thanks for the excellent library @samuelcolvin !
Is this project abandoned or there’s plans to come back to it once pydantic v2 gets settled?
Thanks!

**Comment by JonasKs** [comment]
Arq is used in production at a big scale. It is stable and production ready. 

Please let me know if there’s something specific you really need to be merged (and why🙃), and I’ll look at the PR again as soon as I can, but the reality is that I/we are pretty busy these days.

**Comment by vidjuheffex** [comment]
Some things I think would be neat:
- [more reliable watching of files on the worker. It reloads them, but executes the stale code](https://github.com/samuelcolvin/arq/issues/168) 
- [pubsub support] (https://github.com/samuelcolvin/arq/issues/404)
- [metadata support](https://github.com/samuelcolvin/arq/issues/425)

You can follow these issues to see myself and other users making the cases for the features or fixes.

I see Draft PR's are welcome (so not saying it's not on the community to step up a bit), but I think it's fair for a community to want to get a feel for where this projects future is at.

I recently discovered the library and quite like the API, so I will be looking to see if there are any issues I can tackle. FWIW

**Comment by samuelcolvin** [comment]
@epicwhale we're working on a solution to exactly this problem right now at Pydantic, we hope to make an announcement about this in April, or email me to join the closed beta. samuel@pydantic.dev.

**Comment by samuelcolvin** [comment]
@AlexanderPodorov sorry for the slow reply, and slow progress on arq in general.

> Is this project abandoned or there’s plans to come back to it once pydantic v2 gets settled?

I definitely have plans to restart work on arq and make some significant improvements. I'll post a full plan soon.

**Comment by samuelcolvin** [comment]
See #437 which has a plan for the future of Arq - let's continue the discussion there.

Sorry again for the slow reply.
