### ISSUE TITLE
Duplicate jobs showing in monitor

### ISSUE THREAD

**Issue by younseoryu** [samuelcolvin/arq#421]
<img width="459" alt="Screenshot 2023-11-17 at 9 54 38 PM" src="https://github.com/samuelcolvin/arq/assets/38140590/ac1faac0-84f8-4e24-a413-0b8fe518b455">

<img width="1105" alt="Screenshot 2023-11-17 at 9 54 09 PM" src="https://github.com/samuelcolvin/arq/assets/38140590/795bbd11-c996-4e06-b7dc-f494f6d9697d">

There was one job scheduled with ID job:default:e1c50188-85d6-11ee-8c04-0242c0a8a004.
However, I see a duplicate of it in http://127.0.0.1:8000/monitor/queues/default.
Although i see two, when the job is completed, Completed count gets incremented by 1 only

**Comment by JonasKs** [comment]
Wrong library. Closing.
