### ISSUE TITLE
[Question] Rate limit per job?

### ISSUE THREAD

**Issue by williamle92** [samuelcolvin/arq#426]
Hello,
I have a task/function that sends out emails in batches, the rate limit is permissive but I can think of scenarios where multiple clients trigger this function and can hit the rate limit. Though the email provider did not explicitly state that there would be consequences if the rate limit is hit (e.g. suspend api key), I would like to implement a rate limit to avoid this scenario if possible.

Is it possible to enforce a rate limit on certain tasks? Or allow a max number of jobs allowed to be run for a specific queue?

Thank you!

**Comment by KarlCMB** [comment]
Hi!
check out the max_jobs property of the [worker](https://arq-docs.helpmanual.io/#arq.worker.Worker). 
There you can set a maximum of jobs running at the same time.
This is not a real rate limit, but limits the number of concurrent requests to your mail api.

**Comment by joshwilson-dbx** [comment]
It looks like it's possible to combine that `max_jobs` parameter with `poll_delay` and `queue_read_limit` to enforce a rate ceiling.

**Comment by williamle92** [comment]
Hello, 
Thank you @KarlCMB and @joshwilson-dbx for your response! I will look into this.
