### ISSUE TITLE
cron job with parameter

### ISSUE THREAD

**Issue by fmatten** [samuelcolvin/arq#431]
I tested following situation with partial:

from functools import wraps

def partial(f, *args, **kwargs):
"""
Wrapper for cron functions to inject corellation_id
"""
@wraps(f)
async def partial_function(ctx):
    return await f(*args, **kwargs)

return partial_function

async def my_test_cron_job(ctx, store_id):
print(ctx)
print(store_id)

class WorkerSettings:
cron_jobs = [cron(partial(my_test_cron_job, {}, store_id='826b2e76-be55-42d0-9022-7f7c26b430cd'),
hour=at_every_x_hour(1), minute=at_every_y_minutes(1), run_at_startup=True,
job_id='id1'),
cron(partial(my_test_cron_job, {}, store_id='33beef9c-dfd3-42b7-a78b-706f29f8fcgt'),
hour=at_every_x_hour(1), minute=at_every_y_minutes(1), run_at_startup=True,
job_id='id2'),
]

run_worker(WorkerSettings)

Only the last job parameter will printed twice?

ctx = {}
33beef9c-dfd3-42b7-a78b-706f29f8fcgt
ctx ={}
33beef9c-dfd3-42b7-a78b-706f29f8fcgt

the ctx is empty! #263

**Comment by joshwilson-dbx** [comment]
A few things here:

You're dropping the ctx on the floor. It should be something like this instead:
```python
def partial(f, *args, **kwargs):

    @wraps(f)
    async def partial_function(ctx):
        return await f(ctx, *args, **kwargs)

    return partial_function
```

You're also currently passing in an empty `{}` which is populating your `ctx` parameter, hence the empty context. You don't need that anymore.

Finally, it looks like `arq` uses the job name as a key for its internal lookup tables.  By default, it uses your job function's name. So since you're using the same function twice, the first gets stomped.

Try using the `name=` parameter to `cron()`. To keep with the default convention, you'll probably want to keep the `cron:` prefix:
```python
class WorkerSettings:
    cron_jobs = [
        cron(
            partial(my_test_cron_job, store_id="826b2e76-be55-42d0-9022-7f7c26b430cd"),
            hour=at_every_x_hour(1),
            minute=at_every_y_minutes(1),
            run_at_startup=True,
            job_id="id1",
            name="cron:my_test_cron_job_id1",
        ),
        cron(
            partial(my_test_cron_job, store_id="33beef9c-dfd3-42b7-a78b-706f29f8fcgt"),
            hour=at_every_x_hour(1),
            minute=at_every_y_minutes(1),
            run_at_startup=True,
            job_id="id2",
            name="cron:my_test_cron_job_id2",
        ),
    ]
```

**Comment by fmatten** [comment]
I tested the function from [#263](https://github.com/samuelcolvin/arq/issues/263) last `comment.`

`def partial(f, *args, **kwargs):

    @wraps(f)
    async def partial_function(ctx):
        return await f(ctx, *args, **kwargs)

    return partial_function`

and

`class WorkerSettings:
    cron_jobs = [
        cron(
            partial(my_test_cron_job, store_id="826b2e76-be55-42d0-9022-7f7c26b430cd"),
            hour=at_every_x_hour(1),
            minute=at_every_y_minutes(1),
            run_at_startup=True,
            job_id="id1",
            name="cron:my_test_cron_job_id1",
        ),
        cron(
            partial(my_test_cron_job, store_id="33beef9c-dfd3-42b7-a78b-706f29f8fcgt"),
            hour=at_every_x_hour(1),
            minute=at_every_y_minutes(1),
            run_at_startup=True,
            job_id="id2",
            name="cron:my_test_cron_job_id2",
        ),
    ]`

I revived an error 

`my_test_cron_job() got an unexpected keyword argument 'store_id'`

**Comment by fmatten** [comment]
I tested the last comment from Issue [#263](https://github.com/samuelcolvin/arq/issues/263) .

Now with your correction it is functional

Many Thanks!
